name: jantaengineering CI CD

on:
  push:
    branches:
      - main # Adjust the branch name if needed

env:
  AZURE_WEBAPP_NAME: jantaEngineeringWebsite
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Github Action
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Step 4: Install project dependencies
      - name: Install, Build, and Test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Step 6: Azure Logout
      - name: Azure Logout
        run: az logout
